sudo: false
language: java
jdk:
- oraclejdk8
env:
  global:
  - DITA_OT_VERSION=3.3.1
before_install:
  - chmod +x .travis/install.sh
  - chmod +x .travis/publish.sh
addons:
  apt:
    packages:
      - libxml2-utils
install:
- ".travis/install.sh"
script:
- ".travis/publish.sh"
after_success:
- ""
deploy:
  provider: pages
  local-dir: website
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
  